version: '3.6'
services:
  mongo:
    hostname: mongo
    image: mongo:4.0.10
    ports:
      - "27017:27017"
    networks:
      - backend_network
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 2s
      timeout: 2s
      retries: 200
    command: ["--replSet", "rs0", "--bind_ip_all"]
    extra_hosts:
      - "mongo:127.0.0.1"
    volumes:
      - erxes_mongo_data:/data/db

  redis:
    image: 'redis'
    ports:
      - "6379:6379"
    networks:
      - backend_network
    volumes:
      - erxes_redis_data:/data

  rabbitmq:
    image: rabbitmq:3.7.17-management
    restart: unless-stopped
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - backend_network
    volumes:
      - erxes_rabbitmq_data:/var/lib/rabbitmq

networks:
  backend_network:
    external: true

volumes:
  erxes_mongo_data:
    driver: local
  erxes_redis_data:
    driver: local
  erxes_rabbitmq_data:
    driver: local
